In [1]:
import pandas as pd

In [2]:
dados ={
    'nome':['Joao', 'Maria', 'joao', 'Pedro', 'Ana'],
    'idade':[32, None, 32, 150,28],
    'cidade':['Anápolis', 'Goiânia', 'Anápolis', 'Brasília', 'GOIÂNIA'],
    'salario':[4500,5200,4500,-100,None]

}

In [3]:
df = pd.DataFrame(dados)

In [4]:
df

    nome  idade    cidade  salario
0   Joao   32.0  Anápolis   4500.0
1  Maria    NaN   Goiânia   5200.0
2   joao   32.0  Anápolis   4500.0
3  Pedro  150.0  Brasília   -100.0
4    Ana   28.0   GOIÂNIA      NaN

In [5]:
df.isna()

    nome  idade  cidade  salario
0  False  False   False    False
1  False   True   False    False
2  False  False   False    False
3  False  False   False    False
4  False  False   False     True

In [6]:
df.isna().sum()

nome       0
idade      1
cidade     0
salario    1
dtype: int64

In [7]:
df.isnull()

    nome  idade  cidade  salario
0  False  False   False    False
1  False   True   False    False
2  False  False   False    False
3  False  False   False    False
4  False  False   False     True

In [8]:
percentual = df.isna().mean() * 100
percentual

nome        0.0
idade      20.0
cidade      0.0
salario    20.0
dtype: float64

In [9]:
df['idade'].fillna(30)

0     32.0
1     30.0
2     32.0
3    150.0
4     28.0
Name: idade, dtype: float64