### Importar os pacotes

In [1]:
import pandas as pd

### Criar o dataset

In [2]:
df = pd.DataFrame({
    'cidade': [' São Paulo ','Rio de Janeiro ',' Belo Horizonte']
})

1. Remover espaços.

In [3]:
df['cidade'] = df['cidade'].str.strip()
df

           cidade
0       São Paulo
1  Rio de Janeiro
2  Belo Horizonte

2. Converter para maiúsculo.

In [4]:
df['cidade'] = df['cidade'].str.upper()
df

           cidade
0       SÃO PAULO
1  RIO DE JANEIRO
2  BELO HORIZONTE

3. Converter para minúsculo.