#### Utiliza el DataFrame datos_clima creado en el ejercicio anterior. Aplica los métodos correspondientes para:

1. Extraer exactamente la primera fila de 'datos_clima'. Almacena el contenido en una variable llamada head_df



2. Extraer exactamente la última fila de 'datos_clima'. Almacena el contenido en una variable llamada tail_df

In [3]:
import pandas as pd

In [5]:
datos_clima = pd.read_csv('clima.csv')
head_df = datos_clima.head()
head_df

,region,enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre,anual
0,A CORUNA,240.5,293.4,31.0,80.6,149.5,108.9,44.6,21.8,96.5,154.5,100.8,214.8,1536.9
1,ALBACETE,68.1,28.0,26.2,65.3,25.4,50.0,2.0,34.5,48.0,44.8,33.1,14.1,439.5
2,ALICANTE,49.2,3.7,63.2,85.8,57.2,20.0,9.2,5.0,44.0,41.1,47.4,1.8,427.6
3,ALMERIA,56.3,5.2,35.8,43.1,38.8,16.9,10.2,1.9,17.4,27.3,32.6,3.2,288.7
4,ARABA,96.8,79.9,38.0,52.0,37.7,107.8,8.5,17.7,63.3,38.5,212.2,197.3,949.7

In [6]:
tail_df = datos_clima.tail()
tail_df

,region,enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre,anual
47,TOLEDO,83.0,51.1,7.5,62.5,15.0,27.1,3.3,18.6,70.5,94.7,16.4,29.9,479.6
48,VALENCIA,61.9,16.8,49.3,86.4,33.8,34.2,17.1,30.9,99.3,46.1,46.6,5.5,527.9
49,VALLADOLID,29.2,69.1,4.1,65.1,24.3,58.3,1.9,3.8,54.1,40.2,41.7,35.9,427.7
50,ZAMORA,53.0,112.0,6.8,63.7,19.8,54.2,3.1,9.6,78.5,55.3,29.0,50.3,535.3
51,ZARAGOZA,52.0,30.0,3.6,52.7,38.3,57.5,13.5,13.2,61.5,27.4,76.6,23.4,449.7