## Exercício: Limpeza de Dados de Clientes

In [58]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'id': [1, 2, 3, 4, 5, 5, 7, 8],
    'nome': ['Ana', 'Bruno', 'Carlos', np.nan, 'Eduarda', 'Eduarda', 'Felipe', 'Gabriela'],
    'idade': [25, 30, np.nan, 40, 150, 150, 28, None],
    'salario': [3500, 4200, 3800, None, 5000, 5000, -1000, 4500],
    'cidade': ['São Paulo', 'Rio de Janeiro', 'São Paulo', 'Curitiba', 'Curitiba', 'Curitiba', 'Belo Horizonte', 'Belo Horizonte']
})

df

   id      nome  idade  salario          cidade
0   1       Ana   25.0   3500.0       São Paulo
1   2     Bruno   30.0   4200.0  Rio de Janeiro
2   3    Carlos    NaN   3800.0       São Paulo
3   4       NaN   40.0      NaN        Curitiba
4   5   Eduarda  150.0   5000.0        Curitiba
5   5   Eduarda  150.0   5000.0        Curitiba
6   7    Felipe   28.0  -1000.0  Belo Horizonte
7   8  Gabriela    NaN   4500.0  Belo Horizonte

# 1. Análise inicial

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       8 non-null      int64
 1   nome     7 non-null      object
 2   idade    6 non-null      float64
 3   salario  7 non-null      float64
 4   cidade   8 non-null      object
dtypes: float64(2), int64(1), object(2)
memory usage: 452.0+ bytes

In [60]:
df.describe()

             id       idade      salario
count  8.000000    6.000000     7.000000
mean   4.375000   70.500000  3571.428571
std    2.386719   61.785921  2093.413708
min    1.000000   25.000000 -1000.000000
25%    2.750000   28.500000  3650.000000
50%    4.500000   35.000000  4200.000000
75%    5.500000  122.500000  4750.000000
max    8.000000  150.000000  5000.000000

### 2. Verifique valores ausentes

In [64]:
null_values = df.isnull().sum()
null_values

id         0
nome       1
idade      2
salario    1
cidade     0
dtype: int64

# 3. Trate os valores ausentes
- Preencha as idades faltantes com a média das idades válidas.
- Preencha os salários faltantes com a mediana.