Formação Cientista de Dados - Fernando Amaral e Jones Granatyr
Limpeza e tratamento de Dados

In [1]:
import pandas as pd
import seaborn as srn
import statistics  as sts

In [2]:
#importar dados
dataset = pd.read_csv("Churn.csv", sep=";")
#visulizar
dataset.head()

   X0   X1  X2        X3  X4  X4.1        X6  X7  X8  X9         X10  X11
0   1  619  RS  Feminino  42     2         0   1   1   1  10134888.0    1
1   2  608  SC  Feminino  41     1   8380786   1   0   1  11254258.0    0
2   3  502  RS  Feminino  42     8   1596608   3   1   0  11393157.0    1
3   4  699  RS  Feminino  39     1         0   2   0   0   9382663.0    0
4   5  850  SC  Feminino  43     2  12551082   1   1   1    790841.0    0

In [3]:
#tamanho
dataset.shape

(999, 12)

In [4]:
#primeiro problema é dar nomes as colunas
dataset.columns = ["Id","Score","Estado","Genero","Idade","Patrimonio","Saldo","Produtos","TemCartCredito",
                    "Ativo","Salario","Saiu"]

In [5]:
#visulizar
dataset.head()

,Id,Score,Estado,Genero,Idade,Patrimonio,Saldo,Produtos,TemCartCredito,Ativo,Salario,Saiu
0,1,619,RS,Feminino,42,2,0,1,1,1,10134888.0,1
1,2,608,SC,Feminino,41,1,8380786,1,0,1,11254258.0,0
2,3,502,RS,Feminino,42,8,1596608,3,1,0,11393157.0,1
3,4,699,RS,Feminino,39,1,0,2,0,0,9382663.0,0
4,5,850,SC,Feminino,43,2,12551082,1,1,1,790841.0,0

In [6]:
#explorar dados categoricos
#estado
agrupado = dataset.groupby(['Estado']).size()
agrupado

Estado
PR    257
RP      1
RS    478
SC    258
SP      4
TD      1
dtype: int64

In [ ]:
agrupado.plot.bar(color = 'gray')

In [ ]:
#genero
agrupado = dataset.groupby(['Genero']).size()
agrupado

In [ ]:
agrupado.plot.bar(color = 'gray')

In [ ]:
#explorar colunas numéricas
#score
dataset['Score'].describe()

In [ ]:
srn.boxplot(dataset['Score']).set_title('Score')

In [ ]:
srn.distplot(dataset['Score']).set_title('Score')

In [ ]:
#idade
dataset['Idade'].describe()

In [ ]:
srn.boxplot(dataset['Idade']).set_title('Idade')

In [ ]:
srn.distplot(dataset['Idade']).set_title('Idade')

In [ ]:
#saldo
dataset['Saldo'].describe()

In [ ]:
srn.boxplot(dataset['Saldo']).set_title('Saldo')

In [ ]:
srn.distplot(dataset['Saldo']).set_title('Saldo')

In [ ]:
#salário
dataset['Salario'].describe()

In [ ]:
srn.boxplot(dataset['Salario']).set_title('Salario')

In [ ]:
srn.distplot(dataset['Salario']).set_title('Salario')

In [ ]:
#contamos valores NAN
#genero e salário
dataset.isnull().sum()

In [ ]:
#salarios
#remover nas e substiutir pela mediana
dataset['Salario'].describe()

In [ ]:
mediana = sts.median(dataset['Salario'])
mediana

In [ ]:
#substituir NAN por mediana
dataset['Salario'].fillna(mediana, inplace=True)

In [ ]:
#Verificamos se NAN não existem mais
dataset['Salario'].isnull().sum()

In [ ]:
#genero, falta de padronização e NAs
agrupado = dataset.groupby(['Genero']).size()
agrupado

In [ ]:
#total de Nas
dataset['Genero'].isnull().sum()

In [ ]:
#preenche NAs com Masculino (moda)
dataset['Genero'].fillna('Masculino', inplace=True)

In [ ]:
#verificamos novamente NANs
dataset['Genero'].isnull().sum()

In [ ]:
#padroniza de acordo com o dominio
dataset.loc[dataset['Genero'] ==  'M', 'Genero'] = "Masculino"
dataset.loc[dataset['Genero'].isin( ['Fem','F']), 'Genero'] = "Feminino"
#visualiza o resultado
agrupado = dataset.groupby(['Genero']).size()
agrupado

In [ ]:
#idades fora do dominio
dataset['Idade'].describe()

In [ ]:
#visualizar 
dataset.loc[(dataset['Idade'] <  0 )  | ( dataset['Idade'] >  120) ]

In [ ]:
#calular a mediana
mediana = sts.median(dataset['Idade'])
mediana

In [ ]:
#substituir
dataset.loc[(dataset['Idade'] <  0 )  | ( dataset['Idade'] >  120), 'Idade'] = mediana

In [ ]:
#verificamos se ainda existem idades fora do domínio
dataset.loc[(dataset['Idade'] <  0 )  | ( dataset['Idade'] >  120) ]

In [ ]:
#dados duplicados, buscamos pelo ID
dataset[dataset.duplicated(['Id'],keep=False)]

In [ ]:
#excluimso pelo ID
dataset.drop_duplicates(subset="Id", keep='first',inplace=True)
#buscamos duplicados 
dataset[dataset.duplicated(['Id'],keep=False)]

In [ ]:
#estado foram do domínio
agrupado = dataset.groupby(['Estado']).size()
agrupado

In [ ]:
#atribuomos RS (moda)
dataset.loc[dataset['Estado'].isin( ['RP','SP','TD']), 'Estado'] = "RS"
agrupado = dataset.groupby(['Estado']).size()

In [ ]:
#verificamos o resultado
agrupado

In [ ]:
#outliers em salário, vamos considerar 2 desvios padrão
desv = sts.stdev(dataset['Salario'])
desv

In [ ]:
#definir padrão como maior que 2 desvios padrão
#checamos se algum atende critério
dataset.loc[dataset['Salario'] >=  2 * desv ]

In [ ]:
#vamos atualiar salarios para mediana, calculamos
mediana = sts.median(dataset['Salario'])
mediana

In [ ]:
#atribumos
dataset.loc[dataset['Salario'] >=  2 * desv, 'Salario'] = mediana
#checamos se algum atende critério
dataset.loc[dataset['Salario'] >=  2 * desv ]

In [ ]:
dataset.head()

In [ ]:
dataset.shape