### 1. Análise de clientes

In [1]:
import pandas as pd

dados = {
    "nome": ["Ana", "Bruno", "Carla", "Diego", "Eva"],
    "idade": [22, 35, 29, 41, 30],
    "cidade": ["São Paulo", "Rio de Janeiro", "São Paulo", "Recife", "Curitiba"],
    "compras": [3, 8, 5, 2, 10],
}

df = pd.DataFrame(dados)

2. Filtre clientes de ``São Paulo``.

In [17]:
df[df['cidade'] == 'São Paulo']

    nome  idade     cidade  compras
0    Ana     22  São Paulo        3
2  Carla     29  São Paulo        5

3. Filtre clientes com mais de ``5`` compras.

In [18]:
df[df['compras']>5]

    nome  idade          cidade  compras
1  Bruno     35  Rio de Janeiro        8
4    Eva     30        Curitiba       10

4. Calcule a média de idade.

In [19]:
df['idade'].mean()

np.float64(31.4)