### Criando nossos dados

In [1]:
import pandas as pd

In [2]:
dados = {
    "horas": [1, 2, 3, 4, 5, 6],
    "nota": [4, 5, 6, 7, 8, 9]
}

In [3]:
df = pd.DataFrame(dados)

df

   horas  nota
0      1     4
1      2     5
2      3     6
3      4     7
4      5     8
5      6     9

### Separando Feature e Target

In [5]:
x = df[['horas']]
x

   horas
0      1
1      2
2      3
3      4
4      5
5      6