- importando pandas

In [1]:
import pandas as pd

- dataset e dataframe

In [3]:
dados = {
    "nome": ["Ana", "Bruno", "Carla", "Diego", "Eva"],
    "idade": [22, 35, 29, 41, 30],
    "cidade": ["São Paulo", "Rio de Janeiro", "São Paulo", "Recife", "Curitiba"],
    "compras": [3, 8, 5, 2, 10],
}

df = pd.DataFrame(dados)

1. Mostre apenas as colunas ``nome`` e ``cidade``.

In [18]:
df.groupby('nome')['cidade'].unique()

nome
Ana           [São Paulo]
Bruno    [Rio de Janeiro]
Carla         [São Paulo]
Diego            [Recife]
Eva            [Curitiba]
Name: cidade, dtype: object

2. Filtre clientes de ``São Paulo``.

In [20]:
Sao_paulo = df[df['cidade'] == 'São Paulo']
Sao_paulo

    nome  idade     cidade  compras
0    Ana     22  São Paulo        3
2  Carla     29  São Paulo        5

3. Filtre clientes com mais de ``5`` compras.

In [21]:
mais_de_cinco = df[df['compras']>5]
mais_de_cinco

    nome  idade          cidade  compras
1  Bruno     35  Rio de Janeiro        8
4    Eva     30        Curitiba       10

4. Calcule a média de idade.

In [22]:
df['idade'].mean()

np.float64(31.4)