### Filtrando e resumindo

- importando pandas

In [1]:
import pandas as pd

- Criando o dataset

In [2]:
dados = {
    "produto": ["Mouse", "Teclado", "Caderno", "Caneta", "Monitor"],
    "categoria": ["Informática", "Informática", "Papelaria", "Papelaria", "Informática"],
    "preco": [50, 120, 25, 5, 900],
    "quantidade": [2, 1, 4, 10, 1],
}

- transformando em dataset utilizavel por pandas

In [3]:
df = pd.DataFrame(dados)

- criando uma nova coluna

In [6]:
df['total_venda'] = df['preco'] * df['quantidade']

In [7]:
df

   produto    categoria  preco  quantidade  total_venda
0    Mouse  Informática     50           2          100
1  Teclado  Informática    120           1          120
2  Caderno    Papelaria     25           4          100
3   Caneta    Papelaria      5          10           50
4  Monitor  Informática    900           1          900

- filtrando parecido com where em sql

In [8]:
informatica = df[df['categoria']=='Informatica']
informatica

Empty DataFrame
Columns: [produto, categoria, preco, quantidade, total_venda]
Index: []

- Estatisticas simples

In [9]:
'Preço médio', df['preco'].mean()

('Preço médio', np.float64(220.0))

In [10]:
'Produto mais caro:', df['preco'].max()

('Produto mais caro:', 900)

In [11]:
'Total vendido:', df['total_venda'].sum()

('Total vendido:', np.int64(1270))

- Agrupamento, parecido com GROUP BY em SQL

In [13]:
resumo = df.groupby('categoria')['total_venda'].sum()
resumo

categoria
Informática    1120
Papelaria       150
Name: total_venda, dtype: int64