In [7]:
import pandas as pd

In [8]:
df = pd.DataFrame({
    'Cidade': ['São Paulo  ', 'Rio de Janeiro ', 'Belo Horizonte ']})

df

            Cidade
0      São Paulo
1  Rio de Janeiro
2  Belo Horizonte

1. Remover os espaços extras

In [12]:
df['Cidade'] = df['Cidade'].str.strip()
df

           Cidade
0       São Paulo
1  Rio de Janeiro
2  Belo Horizonte

2. Converter tudo para MAIÚSCULO

In [14]:
df['Cidade'] = df['Cidade'].str.upper()
df

           Cidade
0       SÃO PAULO
1  RIO DE JANEIRO
2  BELO HORIZONTE

3. Converter tudo para minúsculo

In [15]:
df['Cidade'] = df['Cidade'].str.lower()