In [55]:
import pandas as pd

In [56]:
df = pd.DataFrame({
    'cidade': ['São Paulo  ', 'Rio de Janeiro ', 'Belo Horizonte ']})

df

            cidade
0      São Paulo
1  Rio de Janeiro
2  Belo Horizonte

1. Remover os espaços extras

In [79]:
df.cidade = df.cidade.str.strip()
df

           cidade
0       são paulo
1  rio de janeiro
2  belo horizonte

2. Converter tudo para MAIÚSCULO

In [80]:
df.cidade = df.cidade.str.upper()
df

           cidade
0       SÃO PAULO
1  RIO DE JANEIRO
2  BELO HORIZONTE

3. Converter tudo para minúsculo

In [81]:
df.cidade = df.cidade.str.lower()
df

           cidade
0       são paulo
1  rio de janeiro
2  belo horizonte