Escribe un script en Python usando Pandas para eliminar las filas duplicadas en el conjunto de datos. Almacena el resultado en una variable llamada: `df_sin_duplicados`

In [1]:
data = {
    'ID': [1, 2, 3, 4, 1],
    'Producto': ['Producto A', 'Producto B', 'Producto C', 'Producto D', 'Producto A'],
    'Cantidad': [10, 20, 30, 40, 50],
    'Precio': [100, 200, 300, 400, 100]
}

In [2]:
import pandas as pd

df = pd.DataFrame(data)

df

   ID    Producto  Cantidad  Precio
0   1  Producto A        10     100
1   2  Producto B        20     200
2   3  Producto C        30     300
3   4  Producto D        40     400
4   1  Producto A        50     100

In [14]:
df[df.duplicated(subset=['Producto'])].dropna()

   ID    Producto  Cantidad  Precio
4   1  Producto A        50     100