Escribe un código en Python usando Pandas para reemplazar los valores nulos en la columna Precio por el promedio de los precios no nulos de esa columna.

In [3]:
data = {
    'ID': [1, 2, 3, 4],
    'Producto': ['Producto A', 'Producto B', 'Producto C', 'Producto D'],
    'Cantidad': [10, 20, 30, 40],
    'Precio': [100, None, 300, None]
}

In [4]:
import pandas as pd

df = pd.DataFrame(data)

df

   ID    Producto  Cantidad  Precio
0   1  Producto A        10   100.0
1   2  Producto B        20     NaN
2   3  Producto C        30   300.0
3   4  Producto D        40     NaN

In [7]:
df.isnull()

      ID  Producto  Cantidad  Precio
0  False     False     False   False
1  False     False     False    True
2  False     False     False   False
3  False     False     False    True

In [9]:
df['Precio'] = df['Precio'].fillna(df['Precio'].mean())