In [1]:
import pandas as pd

dados = {
    "nome": [
        "João",
        "Maria",
        "Pedro",
        "João",
        "Ana",
        "Carlos"
    ],
    
    "idade": [
        32,
        None,
        25,
        32,
        None,
        41
    ],
    
    "salario": [
        3500,
        4200,
        None,
        3500,
        2800,
        None
    ]
}

df = pd.DataFrame(dados)

### 1️⃣ Descobrir quantos valores ausentes existem.

In [2]:
sum_of_null =df.isnull().sum()
sum_of_null

nome       0
idade      2
salario    2
dtype: int64

### 2️⃣ Descobrir quantas linhas duplicadas existem.

In [6]:
duplicados = df.duplicated().sum()
duplicados

np.int64(1)

### 3️⃣ Remover os duplicados.

In [7]:
df = df.drop_duplicates()
df

     nome  idade  salario
0    João   32.0   3500.0
1   Maria    NaN   4200.0
2   Pedro   25.0      NaN
4     Ana    NaN   2800.0
5  Carlos   41.0      NaN

### 4️⃣ Substituir os valores ausentes de ``idade`` pela média.

In [8]:
media_idades = df['idade'].mean()
df['idade'] = df['idade'].fillna(media_idades)
df

C:\Users\Olive\AppData\Local\Temp\ipykernel_34376\3167006168.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['idade'] = df['idade'].fillna(media_idades)

     nome      idade  salario
0    João  32.000000   3500.0
1   Maria  32.666667   4200.0
2   Pedro  25.000000      NaN
4     Ana  32.666667   2800.0
5  Carlos  41.000000      NaN