### Criar dataset

In [1]:
import pandas as pd

In [2]:
dados = {
    "nome":["Ana", "João", "Maria"],
    "idade":[25,40,32],
    "salario":[3500,5000,4500]
}

df = pd.DataFrame(dados)
df

    nome  idade  salario
0    Ana     25     3500
1   João     40     5000
2  Maria     32     4500

In [3]:
df.tail()

    nome  idade  salario
0    Ana     25     3500
1   João     40     5000
2  Maria     32     4500

In [5]:
df.shape

(3, 3)

In [6]:
df.columns

Index(['nome', 'idade', 'salario'], dtype='object')

In [7]:
list(df.columns)

['nome', 'idade', 'salario']

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   nome     3 non-null      object
 1   idade    3 non-null      int64
 2   salario  3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

In [9]:
df.describe()

           idade      salario
count   3.000000     3.000000
mean   32.333333  4333.333333
std     7.505553   763.762616
min    25.000000  3500.000000
25%    28.500000  4000.000000
50%    32.000000  4500.000000
75%    36.000000  4750.000000
max    40.000000  5000.000000