In [28]:
import pandas as pd

In [29]:
cidades ={'cidade':["Goiânia", "Anápolis", "Goiânia", "Brasília", "Anápolis"]}

In [30]:
df = pd.DataFrame(cidades)
df

     cidade
0   Goiânia
1  Anápolis
2   Goiânia
3  Brasília
4  Anápolis

In [31]:
df['cidade'].unique()

array(['Goiânia', 'Anápolis', 'Brasília'], dtype=object)

# Quantidade de cada categoria

In [32]:
df['cidade'].value_counts()

cidade
Goiânia     2
Anápolis    2
Brasília    1
Name: count, dtype: int64

# Criar uma nova categoria

In [35]:
dados = {
    "nome":["Ana", "João", "Maria", "Pedro", "Carlos"],
    "idade":[25,40,32,28,50],
    "salario":[3500,5000,4500,2800,7000]
}

In [37]:
df = pd.DataFrame(dados)
df

     nome  idade  salario
0     Ana     25     3500
1    João     40     5000
2   Maria     32     4500
3   Pedro     28     2800
4  Carlos     50     7000